[package]
name = "rust-warp-sqlx-backend"
version = "0.1.0"
authors = ["许忠亮 <geniusmickymouse@qq.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.11"
# diesel = { version = "=1.4.3", features = ["chrono", "mysql", "r2d2", "uuidv07", "serde_json"] }
dotenv = "0.15.0"
pretty_env_logger = "0.4.0"
log = "0.4"
jsonwebtoken = "7.0.1"
serde = "1.0.114"
serde_derive = "1.0.114"
tokio = { version = "0.2.21", features = ["macros"] }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
async-trait = "0.1"
warp = "0.2.3"
# warp = { git = "https://github.com/cjbassi/warp", branch = "error" }

db = { package = "realworld-db", path = "./src/db" }
domain = { package = "realworld-domain", path = "./src/domain" }
