use warp::{self, Filter};

use crate::app::AppState;
use crate::handlers;

pub fn routes(
    state: AppState,
) -> impl Filter<Extract = impl warp::Reply, Error = warp::Rejection> + Clone {
    warp::path::end()
        .map(handlers::index::index)
        // .or(warp::path!("api" / "articles")
        //     .and(warp::get())
        //     .and(warp::header::optional("Authorization"))
        //     .and(warp::query())
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::articles::list_articles))
        // .or(warp::path!("api" / "articles")
        //     .and(warp::post())
        //     .and(warp::header("Authorization"))
        //     .and(warp::body::json())
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::articles::insert_article))
        // .or(warp::path!("api" / "articles" / "feed")
        //     .and(warp::get())
        //     .and(warp::header("Authorization"))
        //     .and(warp::query())
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::articles::feed))
        // .or(warp::path!("api" / "articles" / String)
        //     .and(warp::get())
        //     .and(warp::header::optional("Authorization"))
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::articles::get_article))
        // .or(warp::path!("api" / "articles" / String)
        //     .and(warp::put())
        //     .and(warp::header("Authorization"))
        //     .and(warp::body::json())
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::articles::update_article))
        // .or(warp::path!("api" / "articles" / String)
        //     .and(warp::delete())
        //     .and(warp::header("Authorization"))
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::articles::delete_article))
        // .or(warp::path!("api" / "articles" / String / "comments")
        //     .and(warp::get())
        //     .and(warp::header::optional("Authorization"))
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::comments::get))
        // .or(warp::path!("api" / "articles" / String / "comments")
        //     .and(warp::post())
        //     .and(warp::header("Authorization"))
        //     .and(warp::body::json())
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::comments::create))
        // .or(warp::path!("api" / "articles" / String / "comments" / u64)
        //     .and(warp::delete())
        //     .and(warp::header("Authorization"))
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::comments::delete))
        // .or(warp::path!("api" / "articles" / String / "favorite")
        //     .and(warp::post())
        //     .and(warp::header("Authorization"))
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::articles::favorite))
        // .or(warp::path!("api" / "articles" / String / "favorite")
        //     .and(warp::delete())
        //     .and(warp::header("Authorization"))
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::articles::unfavorite))
        // .or(warp::path!("api" / "profiles" / String)
        //     .and(warp::get())
        //     .and(warp::header::optional("Authorization"))
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::profiles::get_profile))
        // .or(warp::path!("api" / "profiles" / String / "follow")
        //     .and(warp::post())
        //     .and(warp::header("Authorization"))
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::profiles::follow))
        // .or(warp::path!("api" / "profiles" / String / "follow")
        //     .and(warp::delete())
        //     .and(warp::header("Authorization"))
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::profiles::unfollow))
        // .or(warp::path!("api" / "tags")
        //     .and(warp::get())
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::articles::tags))
        // .or(warp::path!("api" / "user")
        //     .and(warp::get())
        //     .and(warp::header("Authorization"))
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::users::get_current_user))
        // .or(warp::path!("api" / "user")
        //     .and(warp::put())
        //     .and(warp::header("Authorization"))
        //     .and(warp::body::json())
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::users::update_user))
        // .or(warp::path!("api" / "users")
        //     .and(warp::post())
        //     .and(warp::body::json())
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::users::register))
        // .or(warp::path!("api" / "users" / "login")
        //     .and(warp::post())
        //     .and(warp::body::json())
        //     .and(with_state(state.clone()))
        //     .and_then(handlers::users::login))
        .or(warp::path!("api" / "adventures")
            .and(warp::get())
            .and(warp::header::optional("Authorization"))
            .and(warp::query())
            .and(with_state(state.clone()))
            .and_then(handlers::adventures::list_adventures))
        .or(warp::path!("api" / "adventures")
            .and(warp::put())
            .and(warp::header::optional("Authorization"))
            .and(warp::body::json())
            .and(with_state(state.clone()))
            .and_then(handlers::adventures::update_adventure))
        .or(warp::path!("api" / "adventures")
            .and(warp::post())
            .and(warp::header::optional("Authorization"))
            .and(warp::body::json())
            .and(with_state(state.clone()))
            .and_then(handlers::adventures::insert_adventure))
        .or(warp::path!("api" / "adventures" / u64)
            .and(warp::delete())
            .and(warp::header::optional("Authorization"))
            .and(with_state(state.clone()))
            .and_then(handlers::adventures::delete_adventure))
        .or(warp::path!("api" / "adventures" / u64)
            .and(warp::get())
            .and(warp::header::optional("Authorization"))
            .and(with_state(state.clone()))
            .and_then(handlers::adventures::get_adventure))
        .or(warp::path!("api" / "adventures" / "tabs")
            .and(warp::get())
            .and(warp::header::optional("Authorization"))
            .and_then(handlers::adventures::tabs_adventures))
        .or(warp::path!("api" / "adventures" / "update")
            .and(warp::get())
            .and(warp::header::optional("Authorization"))
            .and(warp::query())
            .and_then(handlers::adventures::version_update_adventures))
        .or(warp::path!("api" / "adventures" / "playlist" / String)
            .and(warp::get())
            .and(warp::header::optional("Authorization"))
            .and(with_state(state.clone()))
            .and_then(handlers::adventures::play_list_adventures))
}

fn with_state(
    state: AppState,
) -> impl Filter<Extract = (AppState,), Error = std::convert::Infallible> + Clone {
    warp::any().map(move || state.clone())
}
